config/routes.rb
Kreubb::Application.routes.draw do
  if Rails.env.development?
    mount Notifications::Preview => 'mail_view'
  end

  get     "ping"        => "sessions#ping",           as: "ping"
  get     "login"       => "sessions#new",            as: "login"
  get     "signup"      => "users#new",               as: "signup"
  post    "login_token" => "sessions#login_token",    as: "login_token"
  post    "pusher/auth" => "sessions#pusher",         as: "pusher_auth"
  delete  "logout"      => "sessions#destroy",        as: "logout"

  resources :messages, except: [:new, :edit] do
    collection do
      get 'page/:page', action: :index
      post :from_email
    end
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'messages#bb'
end

app/models/message.rb
require 'rdiscount'

class Message
  include Mongoid::Document
  include Mongoid::Timestamps

  @@smilies = {
    ':)' => 'smile',
    ':(' => 'frown',
    ':confused:' => 'confused',
    ':mad:' => 'mad',
    ':lol:' => 'lol',
    ':p' =>  'tongue',
    ';)' => 'wink',
    ':D' => 'biggrin',
    ':o' => 'redface',
    ':rolleyes:' => 'rolleyes',
    ':cool:' => 'cool',
    ':eek:' => 'eek',
    ':facepalm:' => 'facepalm'
  }

  belongs_to :user
  has_many :reply_tokens
  delegate :username, :colour, to: :user, prefix: true

  field :text
  field :html
  field :email_html

  index({ user_id: 1 })

  attr_protected :html, :email_html

  scope :list, includes(:user).desc(:created_at)
  scope :recent, desc(:created_at).limit(10)

  before_save :process_text
  validates_presence_of :text

  def as_json(options = nil)
    serializable_hash(options).tap do |hash|
      unless self.user.nil?
        hash[:user] = self.user
      else
        hash[:user] = User.deleted_user
      end
    end
  end

  def self.smilies
    @@smilies
  end

  protected
    def process_text
      value = RDiscount.new(self.text, :autolink).to_html

      value.gsub!(/\r\n?/u, "\n")
      value.gsub!(/([^\n]\n)(?=[^\n])/u, '\1<br />')

      self.email_html = smilie_parse(value, false)
      self.html = smilie_parse(value, true)
    end

    def smilie_parse(text, css=true)
      text.clone.tap do |txt|
        Message.smilies.each do |k, v|
          if css
            txt.gsub! k, "<i class=\"smilie smilies-#{v}\"></i>"
          else
            txt.gsub! k, "<img src=\"#{Settings.assethost.production}/assets/smilies/#{v}.png\" />"
          end
        end
      end
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  layout 'bb', only: ['bb']
  load_and_authorize_resource except: [:from_email]

  skip_before_filter :verify_authenticity_token, only: [:from_email]

  respond_to :json, :html

  # Main app
  def bb
    @messages = @messages.list.limit(30)
    respond_with @messages
  end

  # Archive
  def index
    @messages = @messages.list.page(params[:page] || 1)
    respond_with @messages
  end

  def show
    respond_with @message
  end

  def from_email
    unless params["recipient"].blank? || params["stripped-text"].blank?
      token = params["recipient"].gsub(".reply-message@krisbb.mailgun.org", "")
      text = params["stripped-text"]

      begin
        replytoken = ReplyToken.find_by(token: token)
        message = Message.new(user: replytoken.user, text: text)
        notifier.new_message(message, params) if message.save
      rescue Mongoid::Errors::DocumentNotFound
      end
    end

    render text: "OK"
  end

  def create
    params[:message].delete(["html", "user", "created_at"])
    @message.user = current_user

    if @message.save
      notifier.new_message(@message, params)
    end

    respond_with @message
  end

  def update
    @message.update_attributes(params[:message])
    respond_with @message
  end

  def destroy
    @message.destroy

    notifier.delete_message(@message)
    respond_to do |format|
      format.html { redirect_to messages_path }
      format.json { respond_with @message }
    end
  end
end

app/views/messages/_message.html.erb
<li id="message-<%= message.id %>" class="user<%= message.user_colour %>">
  <%= avatar message.user, :small %>
  <div class="info">
    <div class="username">
      <% if message.user.deleted %>
        <%= message.user_username %>
      <% else %>
        <%= link_to message.user_username, user_path(message.user) %>
      <% end %>
    </div>
    <div class="time">
      <time datetime="<%= message.created_at %>">
        <%= message.created_at.to_s :long_ordinal %>
      </time>
    </div>
  </div>
  <div class="contents">
    <%= raw message.html %>
  </div>
  <% if can? :delete, message %>
    <div class="controls">
      <%= link_to "Delete", message_path(message), method: :delete, confirm: "Are you sure?" %>
    </div>
  <% end %>
</li>

app/views/messages/index.html.erb
<%= paginate @messages %>

<ul class="unstyled messages archive">
  <% @messages.each do |message| %>
    <% message.user = User.deleted_user if message.user.nil? %>
    <%= render message %>
  <% end %>
</ul>

<%= paginate @messages %>