config/routes.rb
Kreubb::Application.routes.draw do
  if Rails.env.development?
    mount Notifications::Preview => 'mail_view'
  end

  get     "ping"        => "sessions#ping",           as: "ping"
  get     "login"       => "sessions#new",            as: "login"
  get     "signup"      => "users#new",               as: "signup"
  post    "login_token" => "sessions#login_token",    as: "login_token"
  post    "pusher/auth" => "sessions#pusher",         as: "pusher_auth"
  delete  "logout"      => "sessions#destroy",        as: "logout"

  resources :messages, except: [:new, :edit] do
    collection do
      get 'page/:page', action: :index
      post :from_email
    end
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'messages#bb'
end

app/models/user.rb
require 'securerandom'

class User
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :messages
  has_many :reply_tokens

  mount_uploader :avatar, AvatarUploader

  field :username
  field :token
  field :admin, type: Boolean,  default: false
  field :colour, type: Integer
  field :notify_me, type: Boolean, default: false

  attr_accessor :remember_me, :password_confirmation, :deleted
  attr_protected :admin

  validates_presence_of :email, if: :notify_me, message: "cannot be blank if you have notification checked"
  validates_presence_of :username
  validates_confirmation_of :password, if: :password
  validates_length_of :password, minimum: 6, maximum: 16, if: :password

  authenticates_with_sorcery!

  before_create :enable_signup
  before_save :generate_token, :generate_colour

  def as_json(options = {})
    included = options[:include] || []
    serializable_hash(options).tap do |hash|
      hash.delete "password"
      hash.delete "crypted_password"
      hash.delete "salt"
      hash.delete "token" unless included.include?(:token)
      hash.delete "unlock_token"
      hash.delete "lock_expires_at"
      hash.delete "failed_logins_count"
      hash.delete "remember_me_token"
      hash.delete "remember_me_token_expires_at"
      hash[:deleted] = true if self.new_record?
    end
  end

  def self.deleted_user
    @@deleted_user ||= self.new(colour: 1, username: "Deleted", deleted: true)
    return @@deleted_user
  end

  def online?
    self.last_activity_at > 15.minutes.ago
  end

  protected
    def enable_signup
      Settings.enable_signup
    end

    def generate_token
      self.token = SecureRandom.base64(15).tr('+/=lIO0', 'pqrsxyz') if self.token.nil?
    end

    def generate_colour
      self.colour = rand 1..5 if self.colour.nil?
      #self.colour = "%06x" % (rand * 0xffffff)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  respond_to :html, :json
  layout 'form', only: [:new, :create]

  def index
    #@users = User.all
    respond_with @users
  end

  def show
    #@user = User.find(params[:id])
    respond_with @user
  end

  def new
    #@user = User.new
    respond_with @user
  end

  def edit
    #@user = User.find(params[:id])
    respond_with @user
  end

  def create
    #@user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        auto_login(@user, params[:user][:remember_me])
        format.html { redirect_to root_path, notice: "Signed up!" }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    #@user = User.find(params[:id])

    if params[:user][:password] && params[:user][:password].empty?
      params[:user].delete :password
      params[:user].delete :password_confirmation
    end

    respond_to do |format|
      if @user.update_attributes(params[:user])
        notifier.update_user(@user)
        format.html { redirect_to root_path, notice: "Settings updated!" }
        format.json { render json: @user, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    #@user = User.find(params[:id])
    @user.destroy
    respond_with @user
  end
end

app/views/users/edit.html.erb
<%= simple_form_for(@user, html: {multipart: true, class: "well", autocomplete: "off"}) do |f| %>
  <fieldset>
    <legend>Edit Account &raquo; <%= @user.username %></legend>

    <div class="form-inputs">
      <%= f.input :password, label: "New password", hint: "Leave blank to keep current password" %>
      <%= f.input :password_confirmation, label: "Confirm new password" %>

      <%= f.input :email, label: "Email" %>

      <%= f.input :notify_me, as: :boolean, label: "Notify me of new messages by email" %>

      <%= f.input :avatar, label: "Set avatar" %>
      <%= f.hidden_field :avatar_cache %>

      <div class="control-group avatar optional">
        <label class="avatar optional control-label">Current Avatar</label>
        <div class="controls">
          <%= avatar @user, :big %>
        </div>
      </div>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Save", class: "btn btn-primary" %>
      <%= link_to "Cancel", user_path(current_user), class: "btn btn-small" %>
    </div>
  </fieldset>
<% end %>

app/views/users/index.html.erb
<div class="well">
  <h2>Users</h2>
  <table class="users table table-striped">
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td>
          <%= avatar user, :small %>
          <strong><%= link_to user.username, user_path(user) %></strong>
          <%= online_bit user %>
        </td>
        <td><a><strong><%= user.messages.count %></strong> posts</a></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<%= simple_form_for(@user, html: {class: "well", autocomplete: "off"}) do |f| %>
  <fieldset>
    <legend>Sign Up</legend>

    <div class="form-inputs">
      <%= f.input :username, label: "Username" %>
      <%= f.input :email, label: "Email" %>
      <%= f.input :password, label: "Password" %>
      <%= f.input :password_confirmation, label: "Password confirmation" %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Sign Up", class: "btn btn-primary" %>
      <%= link_to "Sign In", login_path, class: "btn" if Settings.enable_signup %>
    </div>
  </fieldset>
<% end %>

app/views/users/show.html.erb
<div class="row well user-show">
  <div class="span2 user-sidebar">
    <p><%= avatar @user, :big %></p>
    <h2><%= @user.username %></h2>

    <div class="details">
      <p>
        <i class="fa fa-clock"></i>
        <span>
          Last visit
          <time class="timeago" datetime="<%= @user.last_activity_at %>">
            <%= @user.last_activity_at %>
          </time>
        </span>
      </p>
      <p>
        <i class="fa fa-envelope"></i>
        <span><%= mail_to @user.email %></span>
      </p>
    </div>

    <ul class="stats">
        <li>
          <a href="<%= url_for messages_path %>">
            <strong><%= @user.messages.count %></strong>
            <span>messages</span>
          </a>
        </li>
      </ul>
  </div>

  <div class="span9">
    <div class="user-controls">
      <% if can? :delete, @user %>
        <%= link_to raw('<i class="fa fa-trash-o"></i> ') + "Delete User", user_path(@user), method: :delete,
        confirm: "Are you sure?", class: "btn" %>
      <% end %>
      <% if can? :edit, @user %>
        <%= link_to raw('<i class="fa fa-edit"></i> ') + "User Settings", edit_user_path(@user), class: "btn" %>
      <% end %>
    </div>

    <h4>Recent messages</h4>
    <div class="user-messages">
      <% @user.messages.recent.each do |message| -%>
      <div id="message-<%= message.id %>" class="message">
        <span class="label label-info"><%= message.created_at.to_s :long_ordinal %></span>
        <%= raw message.html %>
      </div>
      <% end -%>
    </div>
  </div>
</div>