config/routes.rb
Kreubb::Application.routes.draw do
  if Rails.env.development?
    mount Notifications::Preview => 'mail_view'
  end

  get     "ping"        => "sessions#ping",           as: "ping"
  get     "login"       => "sessions#new",            as: "login"
  get     "signup"      => "users#new",               as: "signup"
  post    "login_token" => "sessions#login_token",    as: "login_token"
  post    "pusher/auth" => "sessions#pusher",         as: "pusher_auth"
  delete  "logout"      => "sessions#destroy",        as: "logout"

  resources :messages, except: [:new, :edit] do
    collection do
      get 'page/:page', action: :index
      post :from_email
    end
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'messages#bb'
end

app/views/layouts/_nav.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">

      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <a class="brand" href="/">KrisBB</a>

      <div class="nav-collapse">
        <ul class="nav pull-right">
          <li class="dropdown">
            <a href="" class="dropdown-toggle" data-toggle="dropdown">
              <%= avatar(current_user, :thumb) +" "+ current_user.username %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to icon_text("user", "Profile"), user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to icon_text("wrench", "Settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to icon_text("list-alt", "Users"), users_path %></li>
              <li class="divider"></li>
              <li><%= link_to icon_text("power-off", "Log out"),
                logout_path, method: :delete, "data-confirm" => "You sure?", class: "logout-link" %></li>
            </ul>
          </li>
        </ul>

        <ul class="nav">
          <%= nav_li "Archive", messages_path %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js">
<head>
  <title>KrisBB</title>
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render_stats_bar %>
  <%= render partial: "layouts/nav" %>

  <div class="container">
    <%= bootstrap_flash %>
    <%= yield %>
  </div>

  <%= javascript_include_tag "common" %>
</body>
</html>

app/views/layouts/bb.html.erb
<!DOCTYPE html>
<html class="no-js">
<head>
  <title>KrisBB</title>
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">

  <%= stylesheet_link_tag "application", media: "all" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body class="bb">
  <%= render_stats_bar %>
  <%= render partial: "layouts/nav" %>

  <div class="container">
    <div class="row">
      <div class="span12">
        <div id="bb-messages"></div>
        <div id="bb-sendbox"></div>
      </div>
    </div>
  </div>

  <div id="bb-userbar"></div>
  
  <script>
    window.KrisBB = {
      <% cache bootstrap_cache_key(@messages) do %>
      bootstrap: <%= Oj.dump(@messages.as_json, mode: :compat).html_safe %>,
      Settings: <%= Oj.dump(Settings.public, mode: :compat).html_safe %>,
      Smilies: <%= Oj.dump(Message.smilies.keys, mode: :compat).html_safe %>,
      <% end %>
      User: <%= Oj.dump(current_user, mode: :compat).html_safe %>,
      <% cache 'emoji' do %>
      Emoji: <%= Oj.dump(smilie_autocomplete_source, mode: :compat).html_safe %>,
      EmojiTpl: "<li data-value='${insert}'>${name} <img alt='${name}' height='20' src='${image}' width='20' /></li>"
      <% end %>
    };
  </script>
  <script src="https://d3dy5gmtp8yhk7.cloudfront.net/2.0/pusher.min.js"></script>
  <%= javascript_include_tag "application" %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '<%= ENV['GAID'] %>', '<%= ENV['GADOM'] %>');
    ga('send', 'pageview');

  </script>
</body>
</html>

app/views/layouts/form.html.erb
<!DOCTYPE html>
<html class="no-js">
<head>
  <title>KrisBB</title>
  
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div class="form-page">
  <%= render_stats_bar %>

  <%= bootstrap_flash %>
  <%= yield %>
</div>

</body>
</html>